version: '3.8'

services:
  mongo_db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mongo_db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

  redis:
    container_name: redis
    image: redis:7
    env_file:
      - .env
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: currency_api
    volumes:
      - ./api:/home/fastapi/api
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo_db:27017
      - MONGODB_DB=${MONGO_DATABASE}
      - BROKER_URL=${REDIS_URL}
    depends_on:
      - mongo_db  

  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    command: "celery -A scraper.periodical_scraper beat --loglevel DEBUG -s /tmp/celerybeat-schedule"
    environment:
     - BROKER_URL=${REDIS_URL}
     - MONGODB_DB=${MONGO_DATABASE}
     - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo_db:27017/
    volumes:
      - ./scraper:/home/celery/scraper
    depends_on:
      - redis
      - mongo_db

  celery-worker:
    container_name: celery-worker
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    command: "celery -A scraper.periodical_scraper worker --loglevel INFO"
    volumes:
      - ./scraper:/home/celery/scraper
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo_db:27017/
      - BROKER_URL=${REDIS_URL}
      - MONGODB_DB=${MONGO_DATABASE}
    depends_on:
      - redis
      - mongo_db
      

volumes:
  mongo:
  redis:  